# This is a basic workflow to help you get started with Actions

name: CI

on:
  # NOTE: Need to run on a PR so that the ${{ github.head_ref }} (branch) is non-null
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-file:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      # Include the pull request ref in the checkout action to prevent merge commit
      # https://github.com/actions/checkout?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Run steps that make changes to the local repo here.
      - name: Write to a file
        run: |
          echo "Hello, world!" >> README.md

      # Commit all changed files back to the repository
      - uses: planetscale/ghcommit-action@v0.2.0
        with:
          commit_message: "🤖 writing"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: 'README.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
